server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauthdb?createDatabaseIfNotExist=true
    username: root
    password: Supun@123
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always

  jpa:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

    properties:
      show_sql: true
      format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
